// Generates src/lib/lqip.ts: a tiny blurred preview (data URI) per image in public/img.
// The <Img> component paints it instantly, so a slow network shows the picture blurred
// rather than an empty box. Run after adding or replacing images: node scripts/gen-lqip.mjs
import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import sharp from 'sharp'

const ROOT = new URL('../public/img/', import.meta.url).pathname
const walk = (dir) =>
  readdirSync(dir).flatMap((f) => {
    const p = join(dir, f)
    return statSync(p).isDirectory() ? walk(p) : p.endsWith('.webp') ? [p] : []
  })

const files = walk(ROOT).sort()
const out = {}
for (const file of files) {
  const key = relative(ROOT, file)
  const { width, height, hasAlpha } = await sharp(file).metadata()
  const w = 20
  const h = Math.max(1, Math.round((height / width) * w))
  const buf = await sharp(file).resize(w, h, { fit: 'fill' }).webp({ quality: 40, alphaQuality: 40 }).toBuffer()
  out[key] = { d: `data:image/webp;base64,${buf.toString('base64')}`, r: +(width / height).toFixed(4), a: hasAlpha || undefined }
}

const body = Object.entries(out)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join('\n')
writeFileSync(
  new URL('../src/lib/lqip.ts', import.meta.url),
  `/* Generated by scripts/gen-lqip.mjs — do not edit by hand. */\nexport interface Lqip {\n  /** 20px-wide blurred preview as a data URI. */\n  d: string\n  /** width / height */\n  r: number\n  /** true when the source has transparency (a cut-out object, not a photo). */\n  a?: boolean\n}\n\nexport const LQIP: Record<string, Lqip> = {\n${body}\n}\n`,
)
console.log(files.length, 'previews,', Math.round(body.length / 1024), 'kB')
